name: continues integration

on:
  push:
    branches:["main"]
  workflow_dispatch:
jobs:
  compilacion:
    runs-on: ubuntu-latest
    - name: Mensaje De prueba
      run: |
        echo "Hola Prueba"
      
